# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrika_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='YA Metrika ID')),
                ('end_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='End title')),
                ('author', models.CharField(blank=True, max_length=64, null=True, verbose_name='Author')),
                ('keywords', models.CharField(blank=True, max_length=128, null=True, verbose_name='Keywords')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'SEO config',
                'verbose_name_plural': 'SEO configs',
            },
        ),
    ]
